services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Class resolver for all types
    Pimcore\Resolver\ClassResolver: ~

    pimcore.class.resolver:
        alias: Pimcore\Resolver\ClassResolver
        public: public