services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true


    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\SimpleBackendSearchBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']