imports:
  - { resource: default.yaml }
  - { resource: two_factor_authentication.yaml }

monolog:
    handlers:
        error:
            type: stream
            path: "%kernel.logs_dir%/own_php.log"
            level: error